
title: "Mon Site"
description: "C'est un site statique généré par Jekyll."
baseurl: "" 
url: "https://jelalisameh.github.io/github-pokemon" 
markdown: kramdown
theme: minima 

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:year/:month/:day/:title.html
collections:
  my_collection:
    output: true